from flask import Flask, render_template, url_for, redirect, request
import json
from bson import ObjectId


from flask_pymongo import PyMongo
app = Flask(__name__,static_folder='static')

app.config["MONGO_URI"] = "mongodb+srv://computerscienceics4u:nose321@cluster0.rh1oi0j.mongodb.net/terms"
mongo = PyMongo(app)

from bson import ObjectId

class JSONEncoder(json.JSONEncoder):
    def default(self, o):
        if isinstance(o, ObjectId):
            return str(o)
        return json.JSONEncoder.default(self, o)



lists = [
    "DigitalDivide",
    "Cyberbullying",
    "MisinformationandDisinformation",
    "AlgorithmicBias",
    "OnlineRadicalization",
    "NetNeutrality",
    "OnlineCensorshipandFreeSpeech",
    "DigitalAddiction",
    "OnlineScams",
    "OnlineVotingSecurity"
]
try:
    for i in lists:
        mongo.db.create_collection(i)
except :
    print("Error")

def insert_data(collect_name, question, answer):
   
    collect_name.insert_one({"Question": question, "Answer" :answer})
    
insert_data(mongo.db.DigitalDivide, "What are the underlying causes and contributing factors?", "The digital divide is driven by economic disparities that lead to unequal access to technology and the internet. Contributing factors include income inequality, variations in educational opportunities, and differences in infrastructure development between urban and rural areas. Government policies and corporate interests also play a significant role, with inadequate investment in underserved regions further widening the gap.")
insert_data(mongo.db.Cyberbullying, "What are the underlying causes and contributing factors?","Cyberbullying is fueled by the pervasive use of social media and digital communication platforms that provide anonymity and a broad reach for harassers. Contributing factors include the lack of effective regulation and moderation on these platforms, as well as the social dynamics of peer pressure and competition. The anonymity and perceived distance of online interactions often embolden individuals to engage in behavior they might avoid in face-to-face settings.")
insert_data(mongo.db.MisinformationandDisinformation, "What are the underlying causes and contributing factors?","Misinformation and disinformation spread rapidly due to the democratization of content creation and the algorithms that favor sensational, engaging content. Factors contributing to this issue include the decline in traditional journalism's gatekeeping role, the rise of social media platforms, and the ease with which false information can be shared. Societal polarization and declining trust in institutions further exacerbate the problem.")
insert_data(mongo.db.AlgorithmicBias, "What are the underlying causes and contributing factors?","Algorithmic bias results from the data used to train AI systems, which often reflect existing societal prejudices and inequalities. Contributing factors include the lack of diversity in the tech industry, insufficient transparency in algorithm development, and the complexity of ensuring fair representation in datasets. These biases are perpetuated when algorithms make decisions based on skewed or incomplete data.")
insert_data(mongo.db.OnlineRadicalization, "What are the underlying causes and contributing factors?","Online radicalization is driven by the internet's ability to connect like-minded individuals and expose users to extremist ideologies through echo chambers and algorithm-driven content recommendations. Contributing factors include social isolation, political polarization, and the anonymity provided by online platforms. These environments facilitate the spread of radical ideologies to susceptible individuals.")
insert_data(mongo.db.NetNeutrality, "What are the underlying causes and contributing factors?","Net neutrality is challenged by the economic interests of major internet service providers (ISPs) who seek to monetize data traffic by prioritizing certain content or services. Contributing factors include deregulation trends, consolidation in the telecom industry, and the increasing influence of a few tech giants. These factors create an environment where ISPs can potentially undermine the principle of an open and equal internet.")
insert_data(mongo.db.OnlineCensorshipandFreeSpeech, "What are the underlying causes and contributing factors?","Online censorship and free speech issues arise from efforts by governments and corporations to control content for political, moral, or economic reasons. Contributing factors include national security concerns, intellectual property rights, and attempts to curb misinformation and hate speech. The balance between protecting free speech and preventing harmful content is influenced by cultural norms, legal frameworks, and political climates.")
insert_data(mongo.db.DigitalAddiction, "What are the underlying causes and contributing factors?","Digital addiction is driven by the widespread use of technology and the internet, which are designed to capture and retain user attention through engaging and rewarding experiences. Contributing factors include the psychological tactics employed by social media and gaming platforms, such as variable rewards and social validation. The normalization of constant connectivity and the pressure to maintain an online presence exacerbate the problem.")
insert_data(mongo.db.OnlineScams, "What are the underlying causes and contributing factors?","Online scams proliferate due to the anonymity and broad reach of the internet, which allow scammers to target victims across the globe. Contributing factors include the lack of digital literacy among users, insufficient cybersecurity measures, and the sophistication of scam techniques. The rapid evolution of technology often outpaces the ability of individuals and organizations to protect themselves from these threats.")
insert_data(mongo.db.OnlineVotingSecurity,"What are the underlying causes and contributing factors?", "Online voting security issues stem from the inherent vulnerabilities of digital systems, which can be exploited by hackers and malicious actors. Contributing factors include inadequate cybersecurity measures, the complexity of ensuring a secure and anonymous voting process, and the potential for large-scale disruptions. The reliance on technology for critical democratic processes amplifies the need for robust security protocols to maintain trust in electoral outcomes.")
insert_data(mongo.db.OnlineScams, "THe question is presented in a way of understanding to the raeser of the main the channnel on the mic bases", "Online voting security issues stem from the inherent vulnerabilities of digital systems, which can be exploited by hackers and malicious actors. Contributing factors include inadequate cybersecurity measures, the complexity of ensuring a secure and anonymous voting process, and the potential for large-scale disruptions. The reliance on technology for critical democratic processes amplifies the need for robust security protocols to maintain trust in electoral outcomes.")
insert_data(mongo.db.DigitalDivide, "What factors have led to the emergence or exacerbation of this issue?", "The digital divide has been exacerbated by rapid technological advancements that outpace the ability of economically disadvantaged groups to keep up. Factors such as the high cost of devices and internet services, unequal distribution of technological infrastructure, and insufficient digital literacy education contribute to this growing gap. Additionally, policy decisions that fail to prioritize equitable access to technology further widen the divide, particularly in rural and underserved urban areas.")
insert_data(mongo.db.Cyberbullying, "What factors have led to the emergence or exacerbation of this issue?","Cyberbullying has emerged and worsened with the proliferation of social media platforms and online communication tools that provide a broad, often anonymous, reach for bullies. Factors contributing to this include the lack of comprehensive policies and regulations on online behavior, the anonymity and impersonal nature of digital interactions, and the social pressures of online popularity and peer approval. The ease with which harmful content can be created and shared online also plays a significant role.")
insert_data(mongo.db.MisinformationandDisinformation, "What factors have led to the emergence or exacerbation of this issue?","")
insert_data(mongo.db.AlgorithmicBias, "What factors have led to the emergence or exacerbation of this issue?","Algorithmic bias has been exacerbated by the widespread adoption of AI and machine learning technologies that rely on biased datasets. Contributing factors include a lack of diversity among developers, insufficient oversight, and transparency in the development of algorithms, and the complex nature of identifying and correcting biases in large datasets. The focus on efficiency and profit over fairness and equity in tech development also exacerbates this issue.")
insert_data(mongo.db.OnlineRadicalization, "What factors have led to the emergence or exacerbation of this issue?","Online radicalization has intensified due to the internet's ability to connect isolated individuals with extremist groups and ideologies. Factors leading to this include the use of social media algorithms that create echo chambers, the anonymity of online interactions, and the proliferation of extremist content online. Political and social polarization, coupled with disenfranchisement and socio-economic inequalities, further drive individuals toward radical ideologies.")
insert_data(mongo.db.NetNeutrality, "What factors have led to the emergence or exacerbation of this issue?","The net neutrality debate has been exacerbated by the increasing consolidation of the telecom industry and the economic interests of major ISPs. Factors such as deregulation trends, lobbying by powerful tech companies, and the growth of data-heavy services that benefit from prioritized traffic have intensified the issue. The potential for ISPs to prioritize their own services or those of paying partners over others poses a significant threat to the principle of an open internet.")
insert_data(mongo.db.OnlineCensorshipandFreeSpeech, "What factors have led to the emergence or exacerbation of this issue?","Online censorship and free speech issues have intensified due to the global reach of the internet and the varying political and cultural norms regarding acceptable content. Factors such as government efforts to control political discourse, the power of tech giants to moderate content, and the rise of hate speech and misinformation online have contributed to the increased scrutiny and regulation of online speech. The challenge lies in balancing the protection of free speech with the need to prevent harmful content.")
insert_data(mongo.db.DigitalAddiction, "What factors have led to the emergence or exacerbation of this issue?","Digital addiction has worsened with the intentional design of technology and online platforms to capture and retain user attention. Factors such as the use of psychological techniques like variable rewards, the constant connectivity enabled by mobile devices, and the social pressures of maintaining an online presence contribute to the problem. The normalization of heavy technology use in both personal and professional life further exacerbates digital addiction.")
insert_data(mongo.db.OnlineScams, "What factors have led to the emergence or exacerbation of this issue?","The proliferation of online scams has been driven by the anonymity of the internet and the global reach it provides to scammers. Factors such as the increasing sophistication of scam techniques, the lack of digital literacy among users, and insufficient cybersecurity measures contribute to the prevalence of online scams. Additionally, the rapid pace of technological advancement often leaves individuals and organizations vulnerable to new and evolving threats.")
insert_data(mongo.db.OnlineVotingSecurity,"What factors have led to the emergence or exacerbation of this issue?", "Online voting security issues have intensified due to the growing reliance on digital systems for critical democratic processes. Factors such as inadequate cybersecurity measures, the complexity of securing online voting platforms, and the potential for large-scale cyber-attacks contribute to the vulnerabilities in online voting. The challenge of ensuring both security and accessibility in digital voting systems remains a significant concern as more jurisdictions consider or implement online voting options.")
  
insert_data(mongo.db.DigitalDivide, "Are there historical or societal contexts that play a role?", "The digital divide is deeply rooted in historical and societal contexts such as economic inequality, racial segregation, and unequal educational opportunities. Historically, the uneven development of infrastructure and services in rural and marginalized urban areas has perpetuated access disparities. Societal contexts, including systemic poverty and educational inequities, continue to hinder the ability of certain groups to access and effectively utilize digital technologies.")
insert_data(mongo.db.Cyberbullying, "Are there historical or societal contexts that play a role?","Historically, bullying has been a prevalent issue, but the rise of digital communication tools has transformed its nature and reach. Societal contexts, such as the normalization of aggression in media and the anonymity provided by online platforms, exacerbate the issue. The shift from face-to-face interactions to digital communications has also made it easier for bullies to target victims without immediate repercussions, reflecting broader changes in how people interact socially.")
insert_data(mongo.db.MisinformationandDisinformation, "Are there historical or societal contexts that play a role?","Misinformation and disinformation have historical precedents in propaganda and yellow journalism. Societal contexts, such as the decline in trust in traditional media and institutions, coupled with increasing political polarization, play significant roles. The digital age has amplified the impact of these issues by enabling the rapid and widespread dissemination of false information, often unchecked by the gatekeepers of traditional media.")
insert_data(mongo.db.AlgorithmicBias, "Are there historical or societal contexts that play a role?","Algorithmic bias is influenced by historical and societal contexts of discrimination and inequality. Historically, biases in data collection and decision-making processes have reflected and reinforced societal prejudices. In the digital age, these biases are embedded in algorithms, often unintentionally perpetuating historical inequities. The lack of diversity in the tech industry and the complexity of algorithms further complicate efforts to address these biases.")
insert_data(mongo.db.OnlineRadicalization, "Are there historical or societal contexts that play a role?","Online radicalization is influenced by historical patterns of social and political extremism. Societal contexts, such as economic disparity, social isolation, and political polarization, create fertile ground for radical ideologies. The internet has provided new platforms for these ideologies to spread, building on historical methods of propaganda and recruitment but with a far greater reach and impact.")
insert_data(mongo.db.NetNeutrality, "Are there historical or societal contexts that play a role?","The debate over net neutrality is rooted in historical conflicts over control and access to communication technologies. Societal contexts, such as the power dynamics between large corporations and consumers, play a critical role. Historically, issues of access and equality have been central to discussions about public utilities and services, and the internet, as a crucial modern utility, is no different.")
insert_data(mongo.db.OnlineCensorshipandFreeSpeech, "Are there historical or societal contexts that play a role?","Online censorship and free speech issues are deeply connected to historical struggles for freedom of expression and government control over information. Societal contexts, such as varying cultural norms and political systems, influence the extent and nature of censorship. The balance between protecting citizens from harmful content and preserving free speech rights continues to be a contentious issue shaped by historical precedents.")
insert_data(mongo.db.DigitalAddiction, "Are there historical or societal contexts that play a role?","Digital addiction reflects historical patterns of behavioral addiction, such as those associated with gambling and substance use. Societal contexts, including the pervasive presence of technology in daily life and the cultural emphasis on connectivity and social media engagement, exacerbate the issue. The design of digital platforms to maximize user engagement taps into historical understandings of addictive behaviors, amplifying their impact in the digital age.")
insert_data(mongo.db.OnlineScams, "Are there historical or societal contexts that play a role?","Online scams have historical analogs in traditional fraud and confidence tricks. Societal contexts, such as the rapid pace of technological change and the lack of widespread digital literacy, play significant roles. Historically, scammers have exploited new communication technologies to reach victims, and the internet provides unprecedented opportunities for such exploitation on a global scale.")
insert_data(mongo.db.OnlineVotingSecurity,"Are there historical or societal contexts that play a role?", "The security of online voting systems is influenced by historical challenges in ensuring the integrity of electoral processes. Societal contexts, including the increasing reliance on technology for critical infrastructure and the evolving nature of cyber threats, play a significant role. Historical experiences with election tampering and fraud underscore the need for robust security measures, while societal trust in democratic processes hinges on the perceived integrity of voting systems.")
  
insert_data(mongo.db.DigitalDivide, "How does this issue affect individuals, communities, or society as a whole?", "digital divide refers to certain communities being able to access the internet. This is mainly an issue in underdeveloped regions where they do not have this access. This is a massive disadvantage which results in many being more isolated, having more difficult access to education, difficulty finding work, and more.")
insert_data(mongo.db.Cyberbullying, "How does this issue affect individuals, communities, or society as a whole?","Cyberbullying has become a major issue over the last several years due to social media. Many people use social media as a gateway to target individuals and marginalized communities online. Cyberbullying can take many forms online but is mainly done through social media platforms.")
insert_data(mongo.db.MisinformationandDisinformation, "How does this issue affect individuals, communities, or society as a whole?","misinformation refers to spreading information that is false. In a world where we have access to the internet, it is sometimes hard to differentiate between what is true and what isn’t. Wikipedia for example is one website that cannot be trusted as anyone can change the information.")
insert_data(mongo.db.AlgorithmicBias, "How does this issue affect individuals, communities, or society as a whole?","Algorithmic bias has to do with artificial intelligence and how it sometimes does not output reliable data, otherwise bias data. This is one of the many concerns with AI and can cause problems involving individuals and marginalized communities.")
insert_data(mongo.db.OnlineRadicalization, "How does this issue affect individuals, communities, or society as a whole?","Online radicalization refers to violence on the internet and is causing issues relating to terrorism, mainly through social media. Many individuals and communities may fall victim to online radicalization and may be targeted online for many reasons.")
insert_data(mongo.db.NetNeutrality, "How does this issue affect individuals, communities, or society as a whole?","Net neutrality refers to all data on the internet being treated equally, mainly by internet service providers and the government. One of the problems regarding this is some service providers have intentionally sped up or slowed down traffic for users. This can cause issues for communities.")
insert_data(mongo.db.OnlineCensorshipandFreeSpeech, "How does this issue affect individuals, communities, or society as a whole?","The major issue with online censorship leaves certain individuals and or communities feeling uncomfortable and unable to freely express themselves online. This is done by restricting their access to sites where they can speak freely.")
insert_data(mongo.db.DigitalAddiction, "How does this issue affect individuals, communities, or society as a whole?","digital addiction is an issue that has become more popular over the last several years. Digital addiction refers to obsession over devices. More notably this includes iphones, tablets, computers, and game consoles. Digital addiction is real and affects many individuals and communities.")
insert_data(mongo.db.OnlineScams, "How does this issue affect individuals, communities, or society as a whole?","online scams are the number one way to scam someone. This is often done via email, phone, or online advertisement. Some scammers can be very good at pretending to be someone they are not and tricking people into giving up private information or installing a virus on the person's device. Communities of older people, and people who are uneducated on technology are the typical targets for these types of scams.")
insert_data(mongo.db.OnlineVotingSecurity,"How does this issue affect individuals, communities, or society as a whole?", "despite the many pros that online voting has, it is also a massive cybersecurity risk as it is hard to monitor. Although online voting can increase accessibility to people, decrease election costs, and help reach underrepresented communities, the risks are just too high and online voting should not go forward.")
  
insert_data(mongo.db.DigitalDivide, "What is the public perception and awareness of the issue?", "Most people are not very aware of this issue. Especially those of us that do have access to the internet, it may be easy to forget that many people do not, and we must recognize this privilege that we have.")
insert_data(mongo.db.Cyberbullying, "What is the public perception and awareness of the issue?","Cyberbullying is an issue that many people probably know about. It’s something that has been taught about in schools. Despite that, many individuals are still targeted by cyberbullying, and some may not be aware that what they are doing could be classified as cyberbullying.")
insert_data(mongo.db.MisinformationandDisinformation, "What is the public perception and awareness of the issue?","Many people probably are not aware of how common misinformation is and how hard it can be to differentiate between what is true and what is false on the internet. It can be extremely easy to believe everything that is read on the internet, more people should be educated on how to spot sources that may not be trustworthy.")
insert_data(mongo.db.AlgorithmicBias, "What is the public perception and awareness of the issue?","This is an issue that more people need to be aware of. As AI is becoming more popular it is important to understand the concerns going on with AI and the potential problems that can occur with AI, such as algorithmic bias.")
insert_data(mongo.db.OnlineRadicalization, "What is the public perception and awareness of the issue?","This is something that probably goes unnoticed by a lot of people, but it is a serious topic. It’s important for people to understand that online radicalization is not just cyberbullying but extreme violence online that can be viewed as terrorism.")
insert_data(mongo.db.NetNeutrality, "What is the public perception and awareness of the issue?","This is a topic that I’m sure many people are unaware of. People may have been victim to this in the past and didn’t realize it. This is why everyone should be educated on net neutrality.")
insert_data(mongo.db.OnlineCensorshipandFreeSpeech, "What is the public perception and awareness of the issue?","Many people are unaware of what kinds of sites accept free speech, and if some aren’t careful, they can be targeted and become victims of cyberbullying depending on what they say online. Despite this, everyone should have some place where they can express themselves.")
insert_data(mongo.db.DigitalAddiction, "What is the public perception and awareness of the issue?","I’m sure many people are aware of the impact that devices have on our lives, however, some may be completely unaware that they may be suffering from digital addiction. It’s important for everyone to be educated on this issue and be aware of the signs of digital addiction.")
insert_data(mongo.db.OnlineScams, "What is the public perception and awareness of the issue?","People may not be completely aware of how common online scams are. It is important for everyone to be educated on how to spot a potential scam and what to do to avoid it. Most people fall victim to an online scam because it can be very easy if people aren’t careful.")
insert_data(mongo.db.OnlineVotingSecurity,"What is the public perception and awareness of the issue?", "For most people, online voting would be very practical. Many are not aware of the risks involved with online voting. People should be educated on the pros and cons of online voting and the security risks associated with it. In this case, the cons outweigh the pros.")
  
insert_data(mongo.db.DigitalDivide, "Specific Problems and Challenges of Various Digital Issues?", "This refers to the gap between those with and without access to technology, creating limitations in education, employment, and essential services.")
insert_data(mongo.db.Cyberbullying, "Specific Problems and Challenges of Various Digital Issues?","The use of electronic communication to bully someone, involving intimidation, threats, and social exclusion, causing significant emotional harm.")
insert_data(mongo.db.MisinformationandDisinformation, "Specific Problems and Challenges of Various Digital Issues?","The spread of inaccurate or misleading information, often unintentional (misinformation) or deliberate (disinformation) to deceive or manipulate.")
insert_data(mongo.db.AlgorithmicBias, "Specific Problems and Challenges of Various Digital Issues?","Algorithms can perpetuate biases present in the data they are trained on, leading to discriminatory outcomes in areas like search results, hiring decisions, or loan approvals.")
insert_data(mongo.db.OnlineRadicalization, "Specific Problems and Challenges of Various Digital Issues?","The process by which someone becomes increasingly extreme in their views, often through exposure to online content that promotes violence or hatred.")
insert_data(mongo.db.NetNeutrality, "Specific Problems and Challenges of Various Digital Issues?","he principle that internet service providers should treat all data equally, not prioritizing certain types of content or throttling speeds. Without it, ISPs could control what users see and do online.")
insert_data(mongo.db.OnlineCensorshipandFreeSpeech, "Specific Problems and Challenges of Various Digital Issues?","The tension between the right to free speech and the need to regulate harmful content online, raising questions about who gets to decide what is acceptable.")
insert_data(mongo.db.DigitalAddiction, "Specific Problems and Challenges of Various Digital Issues?","Excessive use of digital technology that interferes with daily life, causing social, emotional, or physical problems.")
insert_data(mongo.db.OnlineScams, "Specific Problems and Challenges of Various Digital Issues?","Deceptive attempts to manipulate people online for financial gain, targeting individuals or businesses through phishing emails, fake websites, or social engineering tactics.")
insert_data(mongo.db.OnlineVotingSecurity,"Specific Problems and Challenges of Various Digital Issues?", "The potential for vulnerabilities in online voting systems that could be exploited to manipulate election results, raising concerns about the integrity of the democratic process.")
  
insert_data(mongo.db.DigitalDivide, "Are there laws, regulations, or policies related to this issue?", "Policies often focus on increasing affordable internet access and promoting digital literacy skills through subsidies, infrastructure programs, and free training.")
insert_data(mongo.db.Cyberbullying, "Are there laws, regulations, or policies related to this issue?","Existing harassment laws can be applied, and some schools have policies that extend to online behavior. Specific cyberbullying laws exist in some areas, but enforcement challenges remain.")
insert_data(mongo.db.MisinformationandDisinformation, "Are there laws, regulations, or policies related to this issue?","While there are no direct laws against misinformation, some platforms have policies to flag or remove demonstrably false content. Legal issues arise around balancing free speech and content moderation.")
insert_data(mongo.db.AlgorithmicBias, "Are there laws, regulations, or policies related to this issue?","Regulations are emerging to address bias in algorithmic decision-making, particularly in areas like employment or loan approvals.")
insert_data(mongo.db.OnlineRadicalization, "Are there laws, regulations, or policies related to this issue?","Laws targeting hate speech or terrorist content can be relevant, but balancing security and free speech is an ongoing debate.")
insert_data(mongo.db.NetNeutrality, "Are there laws, regulations, or policies related to this issue?","Net neutrality regulations aimed at preventing internet service providers from throttling bandwidth or prioritizing certain content have been repealed in some areas.")
insert_data(mongo.db.OnlineCensorshipandFreeSpeech, "Are there laws, regulations, or policies related to this issue?","Many countries have censorship laws restricting access to certain content, raising concerns about free speech and government control.")
insert_data(mongo.db.DigitalAddiction, "Are there laws, regulations, or policies related to this issue?","Regulations are less common, but some countries are exploring time limits or restrictions on certain features in online games to promote healthier habits.")
insert_data(mongo.db.OnlineScams, "Are there laws, regulations, or policies related to this issue?","Laws against fraud and deception apply online as well, but user awareness and vigilance are crucial.")
insert_data(mongo.db.OnlineVotingSecurity,"Are there laws, regulations, or policies related to this issue?", "Security measures to protect online voting systems and prevent hacking are constantly evolving, with regulations aiming to ensure election integrity.")
  
insert_data(mongo.db.DigitalDivide, "How widespread is this issue, and who is affected by it?", "A global problem, but especially affects low-income communities, rural areas, and older adults.")
insert_data(mongo.db.Cyberbullying, "How widespread is this issue, and who is affected by it?","Studies suggest nearly half of US teens and up to 42% of kids experience it")
insert_data(mongo.db.MisinformationandDisinformation, "How widespread is this issue, and who is affected by it?","A global problem, but some regions and demographics are more susceptible depending on media consumption habits and social circles.")
insert_data(mongo.db.AlgorithmicBias, "How widespread is this issue, and who is affected by it?","Everyone who interacts with algorithms online is affected, but bias can particularly disadvantage marginalized groups in areas like job searches or loan applications.")
insert_data(mongo.db.OnlineRadicalization, "How widespread is this issue, and who is affected by it?","Difficult to quantify, but young people, those isolated or frustrated, and those exposed to extremist content are more susceptible.")
insert_data(mongo.db.NetNeutrality, "How widespread is this issue, and who is affected by it?","Affects everyone who uses the internet, but lack of it can particularly harm those who rely on affordable access to information and services.")
insert_data(mongo.db.OnlineCensorshipandFreeSpeech, "How widespread is this issue, and who is affected by it?","A global debate, but censorship can stifle dissent while free speech can enable online harassment and hate speech. Everyone's access to information and expression is affected.")
insert_data(mongo.db.DigitalAddiction, "How widespread is this issue, and who is affected by it?","While exact numbers are debated, it's a growing concern, impacting anyone who excessively uses technology and struggles to control their online behavior.")
insert_data(mongo.db.OnlineScams, "How widespread is this issue, and who is affected by it?","A global problem affecting people of all ages and backgrounds, but older adults and those with limited technical knowledge can be more vulnerable.")
insert_data(mongo.db.OnlineVotingSecurity,"How widespread is this issue, and who is affected by it?", "Varies by country and voting system. Breaches can impact everyone's faith in the democratic process.")

@app.route("/")
def home():
    return render_template("index.html")
@app.route("/transfer", methods= ["GET","POST"])
def returnFile():
    if request.method == "POST":
        data = request.form["data"]
        print("fjdslkfjdsl")
        return "fdsafsd"
    return render_template("QuestionAnswer.html")
@app.route("/check_database", methods = ["POST"])
def checkdatabase():
    print( request.get_json())
    name = request.get_json()['name']
    collection =  mongo.db.get_collection(name)
    collection.find
    arr = [JSONEncoder().encode(collection.find_one({'Question':"What are the underlying causes and contributing factors?"})),
    JSONEncoder().encode(collection.find_one({'Question':"What factors have led to the emergence or exacerbation of this issue?"})),
    JSONEncoder().encode(collection.find_one({'Question':"Are there historical or societal contexts that play a role?"})),
    JSONEncoder().encode(collection.find_one({'Question':"How does this issue affect individuals, communities, or society as a whole?"})),
    JSONEncoder().encode(collection.find_one({'Question':"What is the public perception and awareness of the issue?"})),
    JSONEncoder().encode(collection.find_one({'Question':"Specific Problems and Challenges of Various Digital Issues?"})),
    JSONEncoder().encode(collection.find_one({'Question':"Are there laws, regulations, or policies related to this issue?"})),
    JSONEncoder().encode(collection.find_one({'Question': "How widespread is this issue, and who is affected by it?"}))
    
    ]
    return  arr
    # run app in debug mode on port 5000
app.run(debug=True, port=5001, host='0.0.0.0')

# @app.route("/ask", methods= ["GET","POST"])
# def checkData():
#     if request.method == "POST":
#         data = request.form["data"]
#         print(data)
#         return render_template("QuestionAnswer.html")