from flask import Flask, render_template, url_for, redirect, request
import json
from bson import ObjectId

from flask import Flask
from flask_pymongo import PyMongo
app = Flask(__name__,static_folder='static')

app.config["MONGO_URI"] = "mongodb+srv://computerscienceics4u:nose321@cluster0.rh1oi0j.mongodb.net/terms"
mongo = PyMongo(app)

from bson import ObjectId

class JSONEncoder(json.JSONEncoder):
    def default(self, o):
        if isinstance(o, ObjectId):
            return str(o)
        return json.JSONEncoder.default(self, o)



lists = [
    "DigitalDivide",
    "Cyberbullying",
    "MisinformationandDisinformation",
    "AlgorithmicBias",
    "OnlineRadicalization",
    "NetNeutrality",
    "OnlineCensorshipandFreeSpeech",
    "DigitalAddiction",
    "OnlineScams",
    "OnlineVotingSecurity"
]
try:
    for i in lists:
        mongo.db.create_collection(i)
except :
    print("Error")

def insert_data(collect_name, question, answer):
    collect_name.insert_one({"Question": question, "Answer" :answer})
    
insert_data(mongo.db.DigitalDivide, "What are the underlying causes and contributing factors?", "The digital divide is driven by economic disparities that lead to unequal access to technology and the internet. Contributing factors include income inequality, variations in educational opportunities, and differences in infrastructure development between urban and rural areas. Government policies and corporate interests also play a significant role, with inadequate investment in underserved regions further widening the gap.")
insert_data(mongo.db.Cyberbullying, "What are the underlying causes and contributing factors?","Cyberbullying is fueled by the pervasive use of social media and digital communication platforms that provide anonymity and a broad reach for harassers. Contributing factors include the lack of effective regulation and moderation on these platforms, as well as the social dynamics of peer pressure and competition. The anonymity and perceived distance of online interactions often embolden individuals to engage in behavior they might avoid in face-to-face settings.")
insert_data(mongo.db.MisinformationandDisinformation, "What are the underlying causes and contributing factors?","Misinformation and disinformation spread rapidly due to the democratization of content creation and the algorithms that favor sensational, engaging content. Factors contributing to this issue include the decline in traditional journalism's gatekeeping role, the rise of social media platforms, and the ease with which false information can be shared. Societal polarization and declining trust in institutions further exacerbate the problem.")
insert_data(mongo.db.AlgorithmicBias, "What are the underlying causes and contributing factors?","Algorithmic bias results from the data used to train AI systems, which often reflect existing societal prejudices and inequalities. Contributing factors include the lack of diversity in the tech industry, insufficient transparency in algorithm development, and the complexity of ensuring fair representation in datasets. These biases are perpetuated when algorithms make decisions based on skewed or incomplete data.")
insert_data(mongo.db.OnlineRadicalization, "What are the underlying causes and contributing factors?","Online radicalization is driven by the internet's ability to connect like-minded individuals and expose users to extremist ideologies through echo chambers and algorithm-driven content recommendations. Contributing factors include social isolation, political polarization, and the anonymity provided by online platforms. These environments facilitate the spread of radical ideologies to susceptible individuals.")
insert_data(mongo.db.NetNeutrality, "What are the underlying causes and contributing factors?","Net neutrality is challenged by the economic interests of major internet service providers (ISPs) who seek to monetize data traffic by prioritizing certain content or services. Contributing factors include deregulation trends, consolidation in the telecom industry, and the increasing influence of a few tech giants. These factors create an environment where ISPs can potentially undermine the principle of an open and equal internet.")
insert_data(mongo.db.OnlineCensorshipandFreeSpeech, "What are the underlying causes and contributing factors?","Online censorship and free speech issues arise from efforts by governments and corporations to control content for political, moral, or economic reasons. Contributing factors include national security concerns, intellectual property rights, and attempts to curb misinformation and hate speech. The balance between protecting free speech and preventing harmful content is influenced by cultural norms, legal frameworks, and political climates.")
insert_data(mongo.db.DigitalAddiction, "What are the underlying causes and contributing factors?","Digital addiction is driven by the widespread use of technology and the internet, which are designed to capture and retain user attention through engaging and rewarding experiences. Contributing factors include the psychological tactics employed by social media and gaming platforms, such as variable rewards and social validation. The normalization of constant connectivity and the pressure to maintain an online presence exacerbate the problem.")
insert_data(mongo.db.OnlineScams, "What are the underlying causes and contributing factors?","Online scams proliferate due to the anonymity and broad reach of the internet, which allow scammers to target victims across the globe. Contributing factors include the lack of digital literacy among users, insufficient cybersecurity measures, and the sophistication of scam techniques. The rapid evolution of technology often outpaces the ability of individuals and organizations to protect themselves from these threats.")
insert_data(mongo.db.OnlineVotingSecurity,"What are the underlying causes and contributing factors?", "Online voting security issues stem from the inherent vulnerabilities of digital systems, which can be exploited by hackers and malicious actors. Contributing factors include inadequate cybersecurity measures, the complexity of ensuring a secure and anonymous voting process, and the potential for large-scale disruptions. The reliance on technology for critical democratic processes amplifies the need for robust security protocols to maintain trust in electoral outcomes.")
  
insert_data(mongo.db.DigitalDivide, "What factors have led to the emergence or exacerbation of this issue?", "The digital divide is driven by economic disparities that lead to unequal access to technology and the internet. Contributing factors include income inequality, variations in educational opportunities, and differences in infrastructure development between urban and rural areas. Government policies and corporate interests also play a significant role, with inadequate investment in underserved regions further widening the gap.")
insert_data(mongo.db.Cyberbullying, "What factors have led to the emergence or exacerbation of this issue?","Cyberbullying is fueled by the pervasive use of social media and digital communication platforms that provide anonymity and a broad reach for harassers. Contributing factors include the lack of effective regulation and moderation on these platforms, as well as the social dynamics of peer pressure and competition. The anonymity and perceived distance of online interactions often embolden individuals to engage in behavior they might avoid in face-to-face settings.")
insert_data(mongo.db.MisinformationandDisinformation, "What factors have led to the emergence or exacerbation of this issue?","Misinformation and disinformation spread rapidly due to the democratization of content creation and the algorithms that favor sensational, engaging content. Factors contributing to this issue include the decline in traditional journalism's gatekeeping role, the rise of social media platforms, and the ease with which false information can be shared. Societal polarization and declining trust in institutions further exacerbate the problem.")
insert_data(mongo.db.AlgorithmicBias, "What factors have led to the emergence or exacerbation of this issue?","Algorithmic bias results from the data used to train AI systems, which often reflect existing societal prejudices and inequalities. Contributing factors include the lack of diversity in the tech industry, insufficient transparency in algorithm development, and the complexity of ensuring fair representation in datasets. These biases are perpetuated when algorithms make decisions based on skewed or incomplete data.")
insert_data(mongo.db.OnlineRadicalization, "What factors have led to the emergence or exacerbation of this issue?","Online radicalization is driven by the internet's ability to connect like-minded individuals and expose users to extremist ideologies through echo chambers and algorithm-driven content recommendations. Contributing factors include social isolation, political polarization, and the anonymity provided by online platforms. These environments facilitate the spread of radical ideologies to susceptible individuals.")
insert_data(mongo.db.NetNeutrality, "What factors have led to the emergence or exacerbation of this issue?","Net neutrality is challenged by the economic interests of major internet service providers (ISPs) who seek to monetize data traffic by prioritizing certain content or services. Contributing factors include deregulation trends, consolidation in the telecom industry, and the increasing influence of a few tech giants. These factors create an environment where ISPs can potentially undermine the principle of an open and equal internet.")
insert_data(mongo.db.OnlineCensorshipandFreeSpeech, "What factors have led to the emergence or exacerbation of this issue?","Online censorship and free speech issues arise from efforts by governments and corporations to control content for political, moral, or economic reasons. Contributing factors include national security concerns, intellectual property rights, and attempts to curb misinformation and hate speech. The balance between protecting free speech and preventing harmful content is influenced by cultural norms, legal frameworks, and political climates.")
insert_data(mongo.db.DigitalAddiction, "What factors have led to the emergence or exacerbation of this issue?","Digital addiction is driven by the widespread use of technology and the internet, which are designed to capture and retain user attention through engaging and rewarding experiences. Contributing factors include the psychological tactics employed by social media and gaming platforms, such as variable rewards and social validation. The normalization of constant connectivity and the pressure to maintain an online presence exacerbate the problem.")
insert_data(mongo.db.OnlineScams, "What factors have led to the emergence or exacerbation of this issue?","Online scams proliferate due to the anonymity and broad reach of the internet, which allow scammers to target victims across the globe. Contributing factors include the lack of digital literacy among users, insufficient cybersecurity measures, and the sophistication of scam techniques. The rapid evolution of technology often outpaces the ability of individuals and organizations to protect themselves from these threats.")
insert_data(mongo.db.OnlineVotingSecurity,"What factors have led to the emergence or exacerbation of this issue?", "Online voting security issues stem from the inherent vulnerabilities of digital systems, which can be exploited by hackers and malicious actors. Contributing factors include inadequate cybersecurity measures, the complexity of ensuring a secure and anonymous voting process, and the potential for large-scale disruptions. The reliance on technology for critical democratic processes amplifies the need for robust security protocols to maintain trust in electoral outcomes.")
  
insert_data(mongo.db.DigitalDivide, "Are there historical or societal contexts that play a role?", "The digital divide is driven by economic disparities that lead to unequal access to technology and the internet. Contributing factors include income inequality, variations in educational opportunities, and differences in infrastructure development between urban and rural areas. Government policies and corporate interests also play a significant role, with inadequate investment in underserved regions further widening the gap.")
insert_data(mongo.db.Cyberbullying, "Are there historical or societal contexts that play a role?","Cyberbullying is fueled by the pervasive use of social media and digital communication platforms that provide anonymity and a broad reach for harassers. Contributing factors include the lack of effective regulation and moderation on these platforms, as well as the social dynamics of peer pressure and competition. The anonymity and perceived distance of online interactions often embolden individuals to engage in behavior they might avoid in face-toAre there historical or societal contexts that play a role?Disinformation")
insert_data(mongo.db.AlgorithmicBias, "Are there historical or societal contexts that play a role?","Algorithmic bias results from the data used to train AI systems, which often reflect existing societal prejudices and inequalities. Contributing factors include the lack of diversity in the tech industry, insufficient transparency in algorithm development, and the complexity of ensuring fair representation in datasets. These biases are perpetuated when algorithms make decisions based on skewed or incomplete data.")
insert_data(mongo.db.OnlineRadicalization, "Are there historical or societal contexts that play a role?","Online radicalization is driven by the internet's ability to connect like-minded individuals and expose users to extremist ideologies through echo chambers and algorithm-driven content recommendations. Contributing factors include social isolation, political polarization, and the anonymity provided by online platforms. These environments facilitate the spread of radical ideologies to susceptible individuals.")
insert_data(mongo.db.NetNeutrality, "Are there historical or societal contexts that play a role?","Net neutrality is challenged by the economic interests of major internet service providers (ISPs) who seek to monetize data traffic by prioritizing certain content or services. Contributing factors include deregulation trends, consolidation in the telecom industry, and the increasing influence of a few tech giants. These factors create an environment where ISPs can potentially undermine the principle of an open and equal internet.")
insert_data(mongo.db.OnlineCensorshipandFreeSpeech, "Are there historical or societal contexts that play a role?","Online censorship and free speech issues arise from efforts by governments and corporations to control content for political, moral, or economic reasons. Contributing factors include national security concerns, intellectual property rights, and attempts to curb misinformation and hate speech. The balance between protecting free speech and preventing harmful content is influenced by cultural norms, legal frameworks, and political climates.")
insert_data(mongo.db.DigitalAddiction, "Are there historical or societal contexts that play a role?","Digital addiction is driven by the widespread use of technology and the internet, which are designed to capture and retain user attention through engaging and rewarding experiences. Contributing factors include the psychological tactics employed by social media and gaming platforms, such as variable rewards and social validation. The normalization of constant connectivity and the pressure to maintain an online presence exacerbate the problem.")
insert_data(mongo.db.OnlineScams, "Are there historical or societal contexts that play a role?","Online scams proliferate due to the anonymity and broad reach of the internet, which allow scammers to target victims across the globe. Contributing factors include the lack of digital literacy among users, insufficient cybersecurity measures, and the sophistication of scam techniques. The rapid evolution of technology often outpaces the ability of individuals and organizations to protect themselves from these threats.")
insert_data(mongo.db.OnlineVotingSecurity,"Are there historical or societal contexts that play a role?", "Online voting security issues stem from the inherent vulnerabilities of digital systems, which can be exploited by hackers and malicious actors. Contributing factors include inadequate cybersecurity measures, the complexity of ensuring a secure and anonymous voting process, and the potential for large-scale disruptions. The reliance on technology for critical democratic processes amplifies the need for robust security protocols to maintain trust in electoral outcomes.")
  
insert_data(mongo.db.DigitalDivide, "How does this issue affect individuals, communities, or society as a whole?", "The digital divide is driven by economic disparities that lead to unequal access to technology and the internet. Contributing factors include income inequality, variations in educational opportunities, and differences in infrastructure development between urban and rural areas. Government policies and corporate interests also play a significant role, with inadequate investment in underserved regions further widening the gap.")
insert_data(mongo.db.Cyberbullying, "How does this issue affect individuals, communities, or society as a whole?","Cyberbullying is fueled by the pervasive use of social media and digital communication platforms that provide anonymity and a broad reach for harassers. Contributing factors include the lack of effective regulation and moderation on these platforms, as well as the social dynamics of peer pressure and competition. The anonymity and perceived distance of online interactions often embolden individuals to engage in behavior they might avoid in face-to-face settings.")
insert_data(mongo.db.MisinformationandDisinformation, "How does this issue affect individuals, communities, or society as a whole?","Misinformation and disinformation spread rapidly due to the democratization of content creation and the algorithms that favor sensational, engaging content. Factors contributing to this issue include the decline in traditional journalism's gatekeeping role, the rise of social media platforms, and the ease with which false information can be shared. Societal polarization and declining trust in institutions further exacerbate the problem.")
insert_data(mongo.db.AlgorithmicBias, "How does this issue affect individuals, communities, or society as a whole?","Algorithmic bias results from the data used to train AI systems, which often reflect existing societal prejudices and inequalities. Contributing factors include the lack of diversity in the tech industry, insufficient transparency in algorithm development, and the complexity of ensuring fair representation in datasets. These biases are perpetuated when algorithms make decisions based on skewed or incomplete data.")
insert_data(mongo.db.OnlineRadicalization, "How does this issue affect individuals, communities, or society as a whole?","Online radicalization is driven by the internet's ability to connect like-minded individuals and expose users to extremist ideologies through echo chambers and algorithm-driven content recommendations. Contributing factors include social isolation, political polarization, and the anonymity provided by online platforms. These environments facilitate the spread of radical ideologies to susceptible individuals.")
insert_data(mongo.db.NetNeutrality, "How does this issue affect individuals, communities, or society as a whole?","Net neutrality is challenged by the economic interests of major internet service providers (ISPs) who seek to monetize data traffic by prioritizing certain content or services. Contributing factors include deregulation trends, consolidation in the telecom industry, and the increasing influence of a few tech giants. These factors create an environment where ISPs can potentially undermine the principle of an open and equal internet.")
insert_data(mongo.db.OnlineCensorshipandFreeSpeech, "How does this issue affect individuals, communities, or society as a whole?","Online censorship and free speech issues arise from efforts by governments and corporations to control content for political, moral, or economic reasons. Contributing factors include national security concerns, intellectual property rights, and attempts to curb misinformation and hate speech. The balance between protecting free speech and preventing harmful content is influenced by cultural norms, legal frameworks, and political climates.")
insert_data(mongo.db.DigitalAddiction, "How does this issue affect individuals, communities, or society as a whole?","Digital addiction is driven by the widespread use of technology and the internet, which are designed to capture and retain user attention through engaging and rewarding experiences. Contributing factors include the psychological tactics employed by social media and gaming platforms, such as variable rewards and social validation. The normalization of constant connectivity and the pressure to maintain an online presence exacerbate the problem.")
insert_data(mongo.db.OnlineScams, "How does this issue affect individuals, communities, or society as a whole?","Online scams proliferate due to the anonymity and broad reach of the internet, which allow scammers to target victims across the globe. Contributing factors include the lack of digital literacy among users, insufficient cybersecurity measures, and the sophistication of scam techniques. The rapid evolution of technology often outpaces the ability of individuals and organizations to protect themselves from these threats.")
insert_data(mongo.db.OnlineVotingSecurity,"How does this issue affect individuals, communities, or society as a whole?", "Online voting security issues stem from the inherent vulnerabilities of digital systems, which can be exploited by hackers and malicious actors. Contributing factors include inadequate cybersecurity measures, the complexity of ensuring a secure and anonymous voting process, and the potential for large-scale disruptions. The reliance on technology for critical democratic processes amplifies the need for robust security protocols to maintain trust in electoral outcomes.")
  
insert_data(mongo.db.DigitalDivide, "What is the public perception and awareness of the issue?", "The digital divide is driven by economic disparities that lead to unequal access to technology and the internet. Contributing factors include income inequality, variations in educational opportunities, and differences in infrastructure development between urban and rural areas. Government policies and corporate interests also play a significant role, with inadequate investment in underserved regions further widening the gap.")
insert_data(mongo.db.Cyberbullying, "What is the public perception and awareness of the issue?","Cyberbullying is fueled by the pervasive use of social media and digital communication platforms that provide anonymity and a broad reach for harassers. Contributing factors include the lack of effective regulation and moderation on these platforms, as well as the social dynamics of peer pressure and competition. The anonymity and perceived distance of online interactions often embolden individuals to engage in behavior they might avoid in face-to-face settings.")
insert_data(mongo.db.MisinformationandDisinformation, "What is the public perception and awareness of the issue?","Misinformation and disinformation spread rapidly due to the democratization of content creation and the algorithms that favor sensational, engaging content. Factors contributing to this issue include the decline in traditional journalism's gatekeeping role, the rise of social media platforms, and the ease with which false information can be shared. Societal polarization and declining trust in institutions further exacerbate the problem.")
insert_data(mongo.db.AlgorithmicBias, "What is the public perception and awareness of the issue?","Algorithmic bias results from the data used to train AI systems, which often reflect existing societal prejudices and inequalities. Contributing factors include the lack of diversity in the tech industry, insufficient transparency in algorithm development, and the complexity of ensuring fair representation in datasets. These biases are perpetuated when algorithms make decisions based on skewed or incomplete data.")
insert_data(mongo.db.OnlineRadicalization, "What is the public perception and awareness of the issue?","Online radicalization is driven by the internet's ability to connect like-minded individuals and expose users to extremist ideologies through echo chambers and algorithm-driven content recommendations. Contributing factors include social isolation, political polarization, and the anonymity provided by online platforms. These environments facilitate the spread of radical ideologies to susceptible individuals.")
insert_data(mongo.db.NetNeutrality, "What is the public perception and awareness of the issue?","Net neutrality is challenged by the economic interests of major internet service providers (ISPs) who seek to monetize data traffic by prioritizing certain content or services. Contributing factors include deregulation trends, consolidation in the telecom industry, and the increasing influence of a few tech giants. These factors create an environment where ISPs can potentially undermine the principle of an open and equal internet.")
insert_data(mongo.db.OnlineCensorshipandFreeSpeech, "What is the public perception and awareness of the issue?","Online censorship and free speech issues arise from efforts by governments and corporations to control content for political, moral, or economic reasons. Contributing factors include national security concerns, intellectual property rights, and attempts to curb misinformation and hate speech. The balance between protecting free speech and preventing harmful content is influenced by cultural norms, legal frameworks, and political climates.")
insert_data(mongo.db.DigitalAddiction, "What is the public perception and awareness of the issue?","Digital addiction is driven by the widespread use of technology and the internet, which are designed to capture and retain user attention through engaging and rewarding experiences. Contributing factors include the psychological tactics employed by social media and gaming platforms, such as variable rewards and social validation. The normalization of constant connectivity and the pressure to maintain an online presence exacerbate the problem.")
insert_data(mongo.db.OnlineScams, "What is the public perception and awareness of the issue?","Online scams proliferate due to the anonymity and broad reach of the internet, which allow scammers to target victims across the globe. Contributing factors include the lack of digital literacy among users, insufficient cybersecurity measures, and the sophistication of scam techniques. The rapid evolution of technology often outpaces the ability of individuals and organizations to protect themselves from these threats.")
insert_data(mongo.db.OnlineVotingSecurity,"What is the public perception and awareness of the issue?", "Online voting security issues stem from the inherent vulnerabilities of digital systems, which can be exploited by hackers and malicious actors. Contributing factors include inadequate cybersecurity measures, the complexity of ensuring a secure and anonymous voting process, and the potential for large-scale disruptions. The reliance on technology for critical democratic processes amplifies the need for robust security protocols to maintain trust in electoral outcomes.")
  
insert_data(mongo.db.DigitalDivide, "Specific Problems and Challenges of Various Digital Issues?", "The digital divide is driven by economic disparities that lead to unequal access to technology and the internet. Contributing factors include income inequality, variations in educational opportunities, and differences in infrastructure development between urban and rural areas. Government policies and corporate interests also play a significant role, with inadequate investment in underserved regions further widening the gap.")
insert_data(mongo.db.Cyberbullying, "Specific Problems and Challenges of Various Digital Issues?","Cyberbullying is fueled by the pervasive use of social media and digital communication platforms that provide anonymity and a broad reach for harassers. Contributing factors include the lack of effective regulation and moderation on these platforms, as well as the social dynamics of peer pressure and competition. The anonymity and perceived distance of online interactions often embolden individuals to engage in behavior they might avoid in face-to-face settings.")
insert_data(mongo.db.MisinformationandDisinformation, "Specific Problems and Challenges of Various Digital Issues?","Misinformation and disinformation spread rapidly due to the democratization of content creation and the algorithms that favor sensational, engaging content. Factors contributing to this issue include the decline in traditional journalism's gatekeeping role, the rise of social media platforms, and the ease with which false information can be shared. Societal polarization and declining trust in institutions further exacerbate the problem.")
insert_data(mongo.db.AlgorithmicBias, "Specific Problems and Challenges of Various Digital Issues?","Algorithmic bias results from the data used to train AI systems, which often reflect existing societal prejudices and inequalities. Contributing factors include the lack of diversity in the tech industry, insufficient transparency in algorithm development, and the complexity of ensuring fair representation in datasets. These biases are perpetuated when algorithms make decisions based on skewed or incomplete data.")
insert_data(mongo.db.OnlineRadicalization, "Specific Problems and Challenges of Various Digital Issues?","Online radicalization is driven by the internet's ability to connect like-minded individuals and expose users to extremist ideologies through echo chambers and algorithm-driven content recommendations. Contributing factors include social isolation, political polarization, and the anonymity provided by online platforms. These environments facilitate the spread of radical ideologies to susceptible individuals.")
insert_data(mongo.db.NetNeutrality, "Specific Problems and Challenges of Various Digital Issues?","Net neutrality is challenged by the economic interests of major internet service providers (ISPs) who seek to monetize data traffic by prioritizing certain content or services. Contributing factors include deregulation trends, consolidation in the telecom industry, and the increasing influence of a few tech giants. These factors create an environment where ISPs can potentially undermine the principle of an open and equal internet.")
insert_data(mongo.db.OnlineCensorshipandFreeSpeech, "Specific Problems and Challenges of Various Digital Issues?","Online censorship and free speech issues arise from efforts by governments and corporations to control content for political, moral, or economic reasons. Contributing factors include national security concerns, intellectual property rights, and attempts to curb misinformation and hate speech. The balance between protecting free speech and preventing harmful content is influenced by cultural norms, legal frameworks, and political climates.")
insert_data(mongo.db.DigitalAddiction, "Specific Problems and Challenges of Various Digital Issues?","Digital addiction is driven by the widespread use of technology and the internet, which are designed to capture and retain user attention through engaging and rewarding experiences. Contributing factors include the psychological tactics employed by social media and gaming platforms, such as variable rewards and social validation. The normalization of constant connectivity and the pressure to maintain an online presence exacerbate the problem.")
insert_data(mongo.db.OnlineScams, "Specific Problems and Challenges of Various Digital Issues?","Online scams proliferate due to the anonymity and broad reach of the internet, which allow scammers to target victims across the globe. Contributing factors include the lack of digital literacy among users, insufficient cybersecurity measures, and the sophistication of scam techniques. The rapid evolution of technology often outpaces the ability of individuals and organizations to protect themselves from these threats.")
insert_data(mongo.db.OnlineVotingSecurity,"Specific Problems and Challenges of Various Digital Issues?", "Online voting security issues stem from the inherent vulnerabilities of digital systems, which can be exploited by hackers and malicious actors. Contributing factors include inadequate cybersecurity measures, the complexity of ensuring a secure and anonymous voting process, and the potential for large-scale disruptions. The reliance on technology for critical democratic processes amplifies the need for robust security protocols to maintain trust in electoral outcomes.")
  
insert_data(mongo.db.DigitalDivide, "Are there laws, regulations, or policies related to this issue?", "The digital divide is driven by economic disparities that lead to unequal access to technology and the internet. Contributing factors include income inequality, variations in educational opportunities, and differences in infrastructure development between urban and rural areas. Government policies and corporate interests also play a significant role, with inadequate investment in underserved regions further widening the gap.")
insert_data(mongo.db.Cyberbullying, "Are there laws, regulations, or policies related to this issue?","Cyberbullying is fueled by the pervasive use of social media and digital communication platforms that provide anonymity and a broad reach for harassers. Contributing factors include the lack of effective regulation and moderation on these platforms, as well as the social dynamics of peer pressure and competition. The anonymity and perceived distance of online interactions often embolden individuals to engage in behavior they might avoid in face-to-face settings.")
insert_data(mongo.db.MisinformationandDisinformation, "Are there laws, regulations, or policies related to this issue?","Misinformation and disinformation spread rapidly due to the democratization of content creation and the algorithms that favor sensational, engaging content. Factors contributing to this issue include the decline in traditional journalism's gatekeeping role, the rise of social media platforms, and the ease with which false information can be shared. Societal polarization and declining trust in institutions further exacerbate the problem.")
insert_data(mongo.db.AlgorithmicBias, "Are there laws, regulations, or policies related to this issue?","Algorithmic bias results from the data used to train AI systems, which often reflect existing societal prejudices and inequalities. Contributing factors include the lack of diversity in the tech industry, insufficient transparency in algorithm development, and the complexity of ensuring fair representation in datasets. These biases are perpetuated when algorithms make decisions based on skewed or incomplete data.")
insert_data(mongo.db.OnlineRadicalization, "Are there laws, regulations, or policies related to this issue?","Online radicalization is driven by the internet's ability to connect like-minded individuals and expose users to extremist ideologies through echo chambers and algorithm-driven content recommendations. Contributing factors include social isolation, political polarization, and the anonymity provided by online platforms. These environments facilitate the spread of radical ideologies to susceptible individuals.")
insert_data(mongo.db.NetNeutrality, "Are there laws, regulations, or policies related to this issue?","Net neutrality is challenged by the economic interests of major internet service providers (ISPs) who seek to monetize data traffic by prioritizing certain content or services. Contributing factors include deregulation trends, consolidation in the telecom industry, and the increasing influence of a few tech giants. These factors create an environment where ISPs can potentially undermine the principle of an open and equal internet.")
insert_data(mongo.db.OnlineCensorshipandFreeSpeech, "Are there laws, regulations, or policies related to this issue?","Online censorship and free speech issues arise from efforts by governments and corporations to control content for political, moral, or economic reasons. Contributing factors include national security concerns, intellectual property rights, and attempts to curb misinformation and hate speech. The balance between protecting free speech and preventing harmful content is influenced by cultural norms, legal frameworks, and political climates.")
insert_data(mongo.db.DigitalAddiction, "Are there laws, regulations, or policies related to this issue?","Digital addiction is driven by the widespread use of technology and the internet, which are designed to capture and retain user attention through engaging and rewarding experiences. Contributing factors include the psychological tactics employed by social media and gaming platforms, such as variable rewards and social validation. The normalization of constant connectivity and the pressure to maintain an online presence exacerbate the problem.")
insert_data(mongo.db.OnlineScams, "Are there laws, regulations, or policies related to this issue?","Online scams proliferate due to the anonymity and broad reach of the internet, which allow scammers to target victims across the globe. Contributing factors include the lack of digital literacy among users, insufficient cybersecurity measures, and the sophistication of scam techniques. The rapid evolution of technology often outpaces the ability of individuals and organizations to protect themselves from these threats.")
insert_data(mongo.db.OnlineVotingSecurity,"Are there laws, regulations, or policies related to this issue?", "Online voting security issues stem from the inherent vulnerabilities of digital systems, which can be exploited by hackers and malicious actors. Contributing factors include inadequate cybersecurity measures, the complexity of ensuring a secure and anonymous voting process, and the potential for large-scale disruptions. The reliance on technology for critical democratic processes amplifies the need for robust security protocols to maintain trust in electoral outcomes.")
  
insert_data(mongo.db.DigitalDivide, "How widespread is this issue, and who is affected by it?", "The digital divide is driven by economic disparities that lead to unequal access to technology and the internet. Contributing factors include income inequality, variations in educational opportunities, and differences in infrastructure development between urban and rural areas. Government policies and corporate interests also play a significant role, with inadequate investment in underserved regions further widening the gap.")
insert_data(mongo.db.Cyberbullying, "How widespread is this issue, and who is affected by it?","Cyberbullying is fueled by the pervasive use of social media and digital communication platforms that provide anonymity and a broad reach for harassers. Contributing factors include the lack of effective regulation and moderation on these platforms, as well as the social dynamics of peer pressure and competition. The anonymity and perceived distance of online interactions often embolden individuals to engage in behavior they might avoid in face-to-face settings.")
insert_data(mongo.db.MisinformationandDisinformation, "How widespread is this issue, and who is affected by it?","Misinformation and disinformation spread rapidly due to the democratization of content creation and the algorithms that favor sensational, engaging content. Factors contributing to this issue include the decline in traditional journalism's gatekeeping role, the rise of social media platforms, and the ease with which false information can be shared. Societal polarization and declining trust in institutions further exacerbate the problem.")
insert_data(mongo.db.AlgorithmicBias, "How widespread is this issue, and who is affected by it?","Algorithmic bias results from the data used to train AI systems, which often reflect existing societal prejudices and inequalities. Contributing factors include the lack of diversity in the tech industry, insufficient transparency in algorithm development, and the complexity of ensuring fair representation in datasets. These biases are perpetuated when algorithms make decisions based on skewed or incomplete data.")
insert_data(mongo.db.OnlineRadicalization, "How widespread is this issue, and who is affected by it?","Online radicalization is driven by the internet's ability to connect like-minded individuals and expose users to extremist ideologies through echo chambers and algorithm-driven content recommendations. Contributing factors include social isolation, political polarization, and the anonymity provided by online platforms. These environments facilitate the spread of radical ideologies to susceptible individuals.")
insert_data(mongo.db.NetNeutrality, "How widespread is this issue, and who is affected by it?","Net neutrality is challenged by the economic interests of major internet service providers (ISPs) who seek to monetize data traffic by prioritizing certain content or services. Contributing factors include deregulation trends, consolidation in the telecom industry, and the increasing influence of a few tech giants. These factors create an environment where ISPs can potentially undermine the principle of an open and equal internet.")
insert_data(mongo.db.OnlineCensorshipandFreeSpeech, "How widespread is this issue, and who is affected by it?","Online censorship and free speech issues arise from efforts by governments and corporations to control content for political, moral, or economic reasons. Contributing factors include national security concerns, intellectual property rights, and attempts to curb misinformation and hate speech. The balance between protecting free speech and preventing harmful content is influenced by cultural norms, legal frameworks, and political climates.")
insert_data(mongo.db.DigitalAddiction, "How widespread is this issue, and who is affected by it?","Digital addiction is driven by the widespread use of technology and the internet, which are designed to capture and retain user attention through engaging and rewarding experiences. Contributing factors include the psychological tactics employed by social media and gaming platforms, such as variable rewards and social validation. The normalization of constant connectivity and the pressure to maintain an online presence exacerbate the problem.")
insert_data(mongo.db.OnlineScams, "How widespread is this issue, and who is affected by it?","Online scams proliferate due to the anonymity and broad reach of the internet, which allow scammers to target victims across the globe. Contributing factors include the lack of digital literacy among users, insufficient cybersecurity measures, and the sophistication of scam techniques. The rapid evolution of technology often outpaces the ability of individuals and organizations to protect themselves from these threats.")
insert_data(mongo.db.OnlineVotingSecurity,"How widespread is this issue, and who is affected by it?", "Online voting security issues stem from the inherent vulnerabilities of digital systems, which can be exploited by hackers and malicious actors. Contributing factors include inadequate cybersecurity measures, the complexity of ensuring a secure and anonymous voting process, and the potential for large-scale disruptions. The reliance on technology for critical democratic processes amplifies the need for robust security protocols to maintain trust in electoral outcomes.")


@app.route("/")
def home():
    return render_template("index.html")
@app.route("/transfer", methods= ["GET","POST"])
def returnFile():
    if request.method == "POST":
        data = request.form["data"]
        print("fjdslkfjdsl")
        return "fdsafsd"
    return render_template("QuestionAnswer.html")
@app.route("/check_database", methods = ["POST"])
def checkdatabase():
    print( request.get_json())
    name = request.get_json()['name']
    collection =  mongo.db.get_collection(name)
    collection.find
    arr = [JSONEncoder().encode(collection.find_one({'Question':"What are the underlying causes and contributing factors?"})),
    JSONEncoder().encode(collection.find_one({'Question':"What factors have led to the emergence or exacerbation of this issue?"})),
    JSONEncoder().encode(collection.find_one({'Question':"Are there historical or societal contexts that play a role?"})),
    JSONEncoder().encode(collection.find_one({'Question':"How does this issue affect individuals, communities, or society as a whole?"})),
    JSONEncoder().encode(collection.find_one({'Question':"What is the public perception and awareness of the issue?"})),
    JSONEncoder().encode(collection.find_one({'Question':"Specific Problems and Challenges of Various Digital Issues?"})),
    JSONEncoder().encode(collection.find_one({'Question':"Are there laws, regulations, or policies related to this issue?"})),
    JSONEncoder().encode(collection.find_one({'Question':"Are there historical or societal contexts that play a role?"}))
    
    ]
    return  arr
    # run app in debug mode on port 5000
app.run(debug=True, port=5001, host='0.0.0.0')

# @app.route("/ask", methods= ["GET","POST"])
# def checkData():
#     if request.method == "POST":
#         data = request.form["data"]
#         print(data)
#         return render_template("QuestionAnswer.html")